### ISSUE TITLE
Presence only data to calculate Boyce Index

### ISSUE THREAD

**Issue by yuliaUU** [AMBarbosa/modEvA#1]
Hi ! 
I wonder if you cna help me with teh following question:

I have presence-only data: I want to calculate Boyce index to evaluate model predictions.
However in your the documentation for `?Boyce` you use the following code:
```
presabs <- mod$y
prediction <- mod$fitted.values

Boyce(obs = presabs, pred = prediction)
```

here your `mod$y` has zeros: but I only have presences and I thought Boyce Index only uses presence only data

**Comment by AMBarbosa** [comment]
Although it's often described as requiring presence-only data, the Boyce index requires the predicted values for the presences AND the predicted values for the rest of the study area (see [this post](https://modtools.wordpress.com/2022/05/06/model-evaluation-with-presence-points-and-raster-predictions/) where I explain this in a bit more detail). Note the bottom of the `?Boyce` help file (and the definitions of the 'obs' and 'pred' arguments), which states that 'obs' can also be a table with just the presence point coordinates, and 'pred' a SpatRaster of the predicted values for the entire study area. But you do need to provide predicted values also at no-presence sites to get the Boyce index, no matter what package or data format you use.
